### ISSUE TITLE
発表スライドの作成

### ISSUE THREAD

**Issue by u-sho** [olff23/oshi-calendar#8]
- Marp/Canva/Google Slide/pandoc/MS Office等好きなツールでok
    - docs ディレクトリにPDFとかhtmlとかmdとかを置いたり置かなかったりする
        - pptx は置かない
- [x] 表紙
- [x] 自己紹介
- [ ] 問題点
- [x] 作ったプロダクトのアイキャッチ
- [x] 詳細（デモ）
- [ ] Q&A（詳細を作りすぎちゃった感じで）

**Comment by olff23** [comment]
- [x] 発表原稿作成

**Comment by u-sho** [comment]
https://www.docswell.com/s/u-sho/5EX4RG-2024-08-03-124540
by olff23
